image: Visual Studio 2017

environment:
  matrix:
  - QTDIR: C:\Qt\5.12.4\msvc2017_64
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    PLATFORM:
    VER_SUFFIX: win64
  - QTDIR: C:\Qt\5.12.4\msvc2017
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat"
    PLATFORM: x86
    VER_SUFFIX: win32

init:
- call "%QTDIR%\bin\qtenv2.bat"
- set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
- call "%VCVARS%" %PLATFORM%

before_build:
- if %APPVEYOR_REPO_TAG% == true (set VERSION=%APPVEYOR_REPO_TAG_NAME%) else for /F %%I in ('git rev-list --count HEAD') do set VERSION=git%%I
- set DEPLOY_DIR=Quaternion-%VERSION%
- git submodule update --init --recursive
- cd lib/3rdparty/libQtOlm
- git clone https://gitlab.matrix.org/matrix-org/olm.git
- cd ../../..
- git clone https://github.com/frankosterfeld/qtkeychain.git
- cd qtkeychain
- cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="install" -DQTKEYCHAIN_STATIC=ON
- cmake --build build --target install
- cd ..

build_script:
- cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="%DEPLOY_DIR%" -DUSE_INTREE_LIBQMC=1 -DQt5Keychain_FOUND=TRUE -DQt5Keychain_DIR="qtkeychain/install/lib/cmake/Qt5Keychain" -DDEPLOY_VERBOSITY=%DEPLOY_VERBOSITY%
- cmake --build build

after_build:
- cmake --build build --target install
- cd "%DEPLOY_DIR%"
- rmdir /S /Q bearer qmltooling
- cd ..
- 7z a quaternion-%VERSION%-%VER_SUFFIX%.zip "%DEPLOY_DIR%"

# Uncomment this to connect to the AppVeyor build worker
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off

artifacts:
- path: quaternion*.zip

deploy:
- provider: Environment
  name: GitHub
  on:
    APPVEYOR_REPO_TAG: true
- provider: Environment
  name: Bintray
  version: "%VERSION%"
  on:
    APPVEYOR_REPO_TAG: false
    branch: master
