language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt571-trusty'
    packages:
    - g++-5
    - qt57-meta-minimal
    - qt57multimedia
    - qt57tools
  homebrew:
    packages:
    - qt5

matrix:
  include:
  - os: linux
    compiler: gcc
    env: [ 'ENV_EVAL="CC=gcc-5 && CXX=g++-5"' ]
  - os: linux
    compiler: clang
  - os: osx
    env: [ 'PATH=/usr/local/opt/qt/bin:$PATH"' ]

before_install:
- eval "${ENV_EVAL}"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then . /opt/qt57/bin/qt57-env.sh; fi

script:
- mkdir build && cd build
- cmake .. -DUSE_INTREE_LIBQMC=1 # TODO: add building with an external lib
- cmake --build . --target all
#- appstream-util validate linux/*.appdata.xml

notifications:
  webhooks:
    urls:
    - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtpdHN1bmUlM0FtYXRyaXgub3JnLyUyMVBDelV0eHRPalV5U3hTZWxvZiUzQW1hdHJpeC5vcmc"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
