language: cpp
dist: bionic

git:
  depth: false

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: 'ppa:beineri/opt-qt597-bionic'
        packages:
        - qt59base
        - qt59imageformats
        - qt59svg
        - qt59multimedia
        - qt59quickcontrols
        - qt59quickcontrols2
        - qt59tools
        - qt5keychain-dev
  - os: linux
    dist: xenial
    compiler: clang
    env: [ 'VERSION_SUFFIX="-compat"', 'BUILD_APPIMAGE=1' ]
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
        packages:
        - mesa-common-dev # Forgotten dep of qt512base
        - qt512base
        - qt512imageformats
        - qt512svg
        - qt512multimedia
        - qt512quickcontrols
        - qt512quickcontrols2
        - qt512tools
        - qt512translations
        - qt5keychain-dev
        - appstream-util
  - os: linux
    compiler: clang
    env: [ 'BUILD_APPIMAGE=1' ]
    addons:
      apt:
        sources:
        - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
        packages:
        - mesa-common-dev # Forgotten dep of qt512base
        - qt512base
        - qt512imageformats
        - qt512svg
        - qt512multimedia
        - qt512quickcontrols
        - qt512quickcontrols2
        - qt512tools
        - qt512translations
        - qt5keychain-dev
        - appstream-util
  - os: osx
    env: [ 'PATH=/usr/local/opt/qt/bin:$PATH' ]
    addons:
      homebrew:
        update: true
        packages:
        - qt5
        - qtkeychain

install:
- pushd lib/3rdparty/libQtOlm
- git clone https://gitlab.matrix.org/matrix-org/olm.git
- popd

before_script:
- if [ -f /opt/qt59/bin/qt59-env.sh ]; then . /opt/qt59/bin/qt59-env.sh; fi
- if [ -f /opt/qt512/bin/qt512-env.sh ]; then . /opt/qt512/bin/qt512-env.sh; fi
# VERSION is also used by linuxdeployqt
- if [ -n "$TRAVIS_TAG" ]; then export VERSION="$TRAVIS_TAG"; else export VERSION="git$(git rev-list --count HEAD)"; fi
- if [ -n "$BUILD_APPIMAGE" ]; then export CMAKE_ARGS="$CMAKE_ARGS -DBUILD_SHARED_LIBS=OFF"; fi

script:
- mkdir build && pushd build
# TODO: add building with an external lib
- cmake .. -LA -DUSE_INTREE_LIBQMC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DDEPLOY_VERBOSITY=$DEPLOY_VERBOSITY $CMAKE_ARGS
- if [ -f "$(which appstream-util)" ]; then appstream-util validate ../linux/*.appdata.xml; fi
- cmake --build . --target all
- export DESTDIR=$TRAVIS_BUILD_DIR/install
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake --build . --target install; fi
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    cmake --build . --target image
    mv -v quaternion.dmg "quaternion-$VERSION.dmg"
  fi
- popd
# TODO: maybe move AppImage generation to CMakeLists.txt
# (pre-wgetting AppImageKit to avoid CMakeList.txt dependency on Internet?)
# FIXME: The AppImageKit downloadables should at the very least be verified
- |
  if [ -n "$BUILD_APPIMAGE" ]; then
    mkdir AppImageKit && pushd AppImageKit
      wget -c -nv \
        "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" \
        "https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so" \
        "https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64"
      chmod a+x ./linuxdeployqt-continuous-x86_64.AppImage
      install -D -m "u=rw,go=r" -t $DESTDIR/usr/optional/libstdc++ /usr/lib/x86_64-linux-gnu/libstdc++.so.6
      install -D -m "u=rw,go=r" ./exec*.so $DESTDIR/usr/optional/exec.so
      install -m "u=rwx,go=rx" ./AppRun* $DESTDIR/AppRun
      unset QTDIR QT_PLUGIN_PATH LD_LIBRARY_PATH
      ./linuxdeployqt-continuous-x86_64.AppImage \
        $DESTDIR/usr/share/applications/*.desktop -appimage -extra-plugins=iconengines,platformthemes/libqgtk3.so -qmldir=$TRAVIS_BUILD_DIR/client/qml -verbose=$DEPLOY_VERBOSITY
      export APPIMAGE_READY=1
    popd
  fi

after_success:
- sed -i -e "s/VERSION_VALUE/$VERSION/g" .ci/bintray-release.json
- sed -i -e "s/VERSION_SUFFIX/$VERSION_SUFFIX/g" .ci/bintray-release.json
- sed -i -e "s/BINTRAY_SUBJECT/$BINTRAY_SUBJECT/g" .ci/bintray-release.json
- sed -i -e "s/BINTRAY_REPO/$BINTRAY_REPO/g" .ci/bintray-release.json
- sed -i -e "s/BINTRAY_NAME/$BINTRAY_NAME/g" .ci/bintray-release.json

deploy:
- provider: bintray
  file: .ci/bintray-release.json
  user: $BINTRAY_USER
  key: $BINTRAY_TOKEN
  skip_cleanup: true
  on:
    tags: false

- provider: releases
  api_key: $GITHUB_API_KEY
  file: build/quaternion-$VERSION.dmg
  skip_cleanup: true
  on:
    tags: true

- provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: AppImageKit/Quaternion*.AppImage
  skip_cleanup: true
  on:
    condition: -n "$RELEASE_APPIMAGE" && -z "$VERSION_SUFFIX"
    tags: true

notifications:
  webhooks:
    urls:
    - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtpdHN1bmUlM0FtYXRyaXgub3JnLyUyMVBDelV0eHRPalV5U3hTZWxvZiUzQW1hdHJpeC5vcmc"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
