language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt571-trusty'
    packages:
    - g++-5
    - qt57-meta-minimal
    - qt57multimedia
    - qt57tools
  homebrew:
    packages:
    - qt5

matrix:
  include:
  - os: linux
    compiler: gcc
    env: [ 'ENV_EVAL="CC=gcc-5 && CXX=g++-5"' ]
  - os: linux
    compiler: clang
    env: [ 'ENV_EVAL="INSTALL_PREFIX=/usr"' ]
  - os: osx
    env: [ 'PATH=/usr/local/opt/qt/bin:$PATH"' ]

before_install:
- eval "${ENV_EVAL}"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then . /opt/qt57/bin/qt57-env.sh; fi

script:
- mkdir build && cd build
- cmake .. -DUSE_INTREE_LIBQMC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX # TODO: add building with an external lib
#- appstream-util validate linux/*.appdata.xml
- cmake --build . --target all
- DESTDIR=install cmake --build . --target install && find install/
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" = "clang" ]; then
    wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    unset QTDIR QT_PLUGIN_PATH LD_LIBRARY_PATH
    export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
    ./linuxdeployqt-continuous-x86_64.AppImage install/usr/share/applications/*.desktop -appimage
    wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh Quaternion*.AppImage*
  fi

notifications:
  webhooks:
    urls:
    - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtpdHN1bmUlM0FtYXRyaXgub3JnLyUyMVBDelV0eHRPalV5U3hTZWxvZiUzQW1hdHJpeC5vcmc"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
