language: cpp

git:
  depth: false

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt571-trusty'
    packages:
    - g++-5
    - qt57-meta-minimal
    - qt57multimedia
    - qt57tools
  homebrew:
    packages:
    - qt5

matrix:
  include:
  - os: linux
    compiler: gcc
    env: [ 'ENV_EVAL="CC=gcc-5 && CXX=g++-5"' ]
  - os: linux
    compiler: clang
    env: [ 'ENV_EVAL="INSTALL_PREFIX=/usr"' ]
  - os: osx
    env: [ 'PATH=/usr/local/opt/qt/bin:$PATH"' ]

before_install:
- eval "${ENV_EVAL}"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then . /opt/qt57/bin/qt57-env.sh; fi

script:
- mkdir build && cd build
- cmake .. -DUSE_INTREE_LIBQMC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX # TODO: add building with an external lib
#- appstream-util validate linux/*.appdata.xml
- cmake --build . --target all
- DESTDIR=install cmake --build . --target install && find install/
- cd $TRAVIS_BUILD_DIR
- export VERSION=$(git rev-parse --count HEAD) # linuxdeployqt uses this for naming the file
- sed -i -e "s/VERSION_VALUE/git-$VERSION/g" .ci/bintray-release.json
- sed -i -e "s/BINTRAY_SUBJECT/$BINTRAY_SUBJECT/g" .ci/bintray-release.json
- sed -i -e "s/BINTRAY_REPO/$BINTRAY_REPO/g" .ci/bintray-release.json
- sed -i -e "s/BINTRAY_NAME/$BINTRAY_NAME/g" .ci/bintray-release.json
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" = "clang" ]; then
    wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    unset QTDIR QT_PLUGIN_PATH LD_LIBRARY_PATH
    ./linuxdeployqt-continuous-x86_64.AppImage install/usr/share/applications/*.desktop -appimage
    export RELEASE_APPIMAGE=1
  fi

deploy:
- provider: bintray
  file: .ci/bintray-release.json
  user: $BINTRAY_USER
  key: $BINTRAY_TOKEN
  skip_cleanup: true
  on:
    tags: false

- provider: releases
  api_key: $GITHUB_API_KEY
  file: build/quaternion.dmg
  skip_cleanup: true
  on:
    tags: true

- provider: releases
  api_key: $GITHUB_API_KEY
  file: Quaternion*.AppImage*
  skip_cleanup: true
  on:
    condition: -n $RELEASE_APPIMAGE
    tags: true

notifications:
  webhooks:
    urls:
    - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtpdHN1bmUlM0FtYXRyaXgub3JnLyUyMVBDelV0eHRPalV5U3hTZWxvZiUzQW1hdHJpeC5vcmc"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
